import type { Metadata } from "next";
import "antd/dist/reset.css";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import GlobalToastContainer from "@/components/common/toast/GlobalToastContainer";
import ClientWrapper from "@/components/wrappers/ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body>
        <ClientWrapper>
          {children}
          <GlobalToastContainer />
        </ClientWrapper>
      </body>
    </html>
  );
}
